version: "2"

services:
  web:
    container_name: "nordisktljus-web"
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    links:
      - mongo
    command: supervisor -w src,index.js index.js

  mongo:
    container_name: "nordisktljud-mongo"
    image: "mongo:latest"
    ports:
      - "27017:27017"
